apiVersion: v1
kind: Service
metadata:
  name: node-red-room1
  namespace: rooms
spec:
  selector:
    app: node-red-room1
  type: NodePort
  ports:
    - name: node-red-ui
      port: 1880
      protocol: TCP
      targetPort: 1880
      nodePort: 30880


