apiVersion: v1
kind: ConfigMap
metadata:
  name: node-red-config
  namespace: rooms
data:
  settings.js: |
    var fs = require("fs");
    module.exports = {
      uiPort: process.env.PORT || 1880,
      mqttReconnectTime: 15000,
      serialReconnectTime: 15000,
      debugMaxLength: 1000,
      adminAuth: {
        type: "credentials",
        users: [{
          username: "admin",
          password: "$2a$08$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN.",
          permissions: "*"
        }]
      },
      httpNodeCors: {
        origin: "*",
        methods: "GET,PUT,POST,DELETE"
      },
      functionGlobalContext: {},
      exportGlobalContextKeys: false,
      logging: {
        console: {
          level: "info",
          metrics: false,
          audit: false
        }
      },
      editorTheme: {
        projects: {
                    // To enable the Projects feature, set this value to true
          enabled: true
        }
      }
    }
