kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30880
    hostPort: 30880
    protocol: TCP
  extraMounts:
  - hostPath: C:\kind_persistent_volume\room1
    containerPath: /var/local-path-provisioner
- role: worker
  extraPortMappings:
  - containerPort: 30474
    hostPort: 30474
    protocol: TCP
  - containerPort: 30473
    hostPort: 30473
    protocol: TCP
  - containerPort: 30687
    hostPort: 30687
    protocol: TCP
  extraMounts:
  - hostPath: C:\kind_persistent_volume\detection-app
    containerPath: /var/local-path-provisioner
  