"""Create a kind cluster config to create a master node is more efficient resoruce
efficient than docker desktop k8s. 
    Author: Thorsten Steuer
    Licence: Apache 2.0
"""
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30880
      hostPort: 30880
      protocol: TCP
    - containerPort: 30474
      hostPort: 30474
      protocol: TCP
    - containerPort: 30473
      hostPort: 30473
      protocol: TCP
    - containerPort: 30687
      hostPort: 30687
      protocol: TCP
  extraMounts:
    - hostPath: C:\kind_persistent_volume\
      containerPath: /var/local-path-provisioner
  