apiVersion: v1
kind: Service
metadata:
  name: mosquitto-broker-service
spec:
  selector:
    app: mosquitto-broker
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
    nodePort: 30883