# Adapted from:
#        https://downey.io/notes/dev/ubuntu-sleep-pod-yaml/
#        [last accessed December 2021]
apiVersion: v1
kind: deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    ports:
      - containerPort: 1883
  restartPolicy: Always
