apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-rooms-config
  namespace: rooms
data:
  mosquitto.conf: |-
    # Port to use for the default listener.
    port 1884

    # Allow anonymous users to connect?
    # If not, the password file should be created
    allow_anonymous true

    # Types of messages to log. Use multiple log_type lines for logging
    # multiple types of messages.
    # Possible types are: debug, error, warning, notice, information,
    # none, subscribe, unsubscribe, websockets, all.
    # Note that debug type messages are for decoding the incoming/outgoing
    # network packets. They are not logged in "topics".
    log_type error
    log_type warning
    log_type notice
    log_type information

    log_dest file /var/log/mosquitto/mosquitto.log

