apiVersion: v1
kind: Service
metadata:
  name: mosquitto-rooms
  namespace: rooms
spec:
  selector:
    app: mosquitto-rooms
  type: NodePort
  ports:
  - port: 1884
    targetPort: 1884
    protocol: TCP
    nodePort: 30884