apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
type: Opaque
data:
  passwd: bTJtLW1xdHQtdXNlcjokNyQxMDEkU1lzUThkNXQ5Wm5DOTltKyREdk1XRXB0b25tdVQwRHFWbVplTW5EUzh3dGpESyt5aHl0QVZoWXFWMjg5Tmp4bDBMRkdBdnhXY0RkVVovMWIxSS9ZckI1aFAwWUthZy9nS2lCWSt4QT09Cg==
