apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-data-pv
  labels:
    type: local
spec:
  storageClassName: mqtt
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/microk8s/volumes/mqtt"
