apiVersion: apps/v1 
kind: Deployment 
metadata:
  labels:
    app: neo4j-db 
  name: neo4j-db 
  namespace: neo4j 
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: neo4j-db
  template:
    metadata:
      labels: 
        app: neo4j-db 
    spec:
      initContainers:
      - name: init-plugins
        image: "appropriate/curl:latest"
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
          - name: neo4j-plugins
            mountPath: /plugins
        command:
          - "/bin/sh"
          - "-c"
          - |
            curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.3.0.3/apoc-4.3.0.3-all.jar -O
            cp -R apoc-4.3.0.3-all.jar /plugins
      containers:
      - image: neo4j:4.3.6-enterprise
        name: neo4j 
        env: 
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
        ports: 
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
        volumeMounts:
            - name: neo4j-plugins
              mountPath: "/var/lib/neo4j/plugins" 
            - name: neo4j-data
              mountPath: "/var/lib/neo4j/data"
      volumes:
          - name: neo4j-data
            persistentVolumeClaim:
              claimName: neo4j-data-claim
          - name: neo4j-plugins
            persistentVolumeClaim:
              claimName: neo4j-plugin-claim
