apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttsa2
  labels:
    app: mqttsa2
  namespace: slowdos-attacker
spec:
  selector:
    matchLabels:
      app: mqttsa2
  template:
    metadata:
      labels:
        app: mqttsa2
    spec:
      containers:
      - name: mqttsa2
        image: bigt1991/mqttsa:latest
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

