kind: Namespace
apiVersion: v1
metadata:
  name: monitoring-system
  labels:
    name: monitoring-system
---
kind: Namespace
apiVersion: v1
metadata:
  name: slowdos-attacker
  labels:
    name: slowdos-attacker
---
kind: Namespace
apiVersion: v1
metadata:
  name: rooms
  labels:
    name: rooms