kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: neo4j-data-claim
  labels:
    app: neo4j-db
  namespace: monitoring-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
  kind: "PersistentVolumeClaim"
  apiVersion: "v1"
  metadata:
    name: neo4j-plugin-claim
    namespace: monitoring-system
    labels:
      app: neo4j-db
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
