apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-app
spec:
  selector:
    matchLabels:
      app: detection-app
  template:
    metadata:
      labels:
        app: detection-app
    spec:
      containers:
      - name: detection-app
        image: bigt1991/idsslowdos:latest
        volumeMounts:
        - name: mosquitto-log-pv
          mountPath: /mosquitto/log
        imagePullPolicy: IfNotPresent
        command: ["/bin/sleep", "3650d"]
      restartPolicy: Always
      volumes:
      - name: mosquitto-log-pv
        persistentVolumeClaim:
          claimName: mosquitto-log-pvc
        

         