apiVersion: v1
kind: Service
metadata:
    name: neo4j-lb
    namespace: neo4j
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 7474
        targetPort: 7474
        name: http
        nodePort: 37474
      - protocol: TCP
        port: 7473
        targetPort: 7473
        name: https
        nodePort: 37473
      - protocol: TCP
        port: 7687
        targetPort: 7687
        name: bolt
        nodePort: 37687
    selector:
      app: neo4j-db