apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-pv
  labels:
    type: local
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/microk8s/volumes/nodered"
