kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  lables:
    app: mosquitto-broker
  name: mosquitto-log-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
